/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single participant's key share */
export interface NapiKeygenOutput {
  key_package: Array<number>
  public_key_package: Array<number>
  identifier: Array<number>
}
/** Output from centralized key generation */
export interface NapiCentralizedKeygenOutput {
  private_key: Array<number>
  keygen_outputs: Array<NapiKeygenOutput>
  public_key: Array<number>
}
/** Generate a 2-of-2 threshold Ed25519 key using centralized key generation. */
export declare function napiKeygenCentralizedEd25519(): NapiCentralizedKeygenOutput
/** Import an existing Ed25519 secret key and split it into threshold shares. */
export declare function napiKeygenImportEd25519(secretKey: Array<number>): NapiCentralizedKeygenOutput
/** Round 1: Generate signing commitments for a participant. */
export declare function napiSignRound1Ed25519(keyPackage: Array<number>): any
/** Round 2: Generate a signature share for a participant. */
export declare function napiSignRound2Ed25519(message: Array<number>, keyPackage: Array<number>, nonces: Array<number>, allCommitments: any): any
/** Aggregate signature shares into a final threshold signature. */
export declare function napiAggregateEd25519(message: Array<number>, allCommitments: any, allSignatureShares: any, publicKeyPackage: Array<number>): any
/** Verify a signature against a public key. */
export declare function napiVerifyEd25519(message: Array<number>, signature: Array<number>, publicKeyPackage: Array<number>): boolean
