export type OkoApiResponse<T> =
  | OkoApiSuccessResponse<T>
  | OkoApiErrorResponse;

export interface OkoApiSuccessResponse<T> {
  success: true;
  data: T;
}

export interface OkoApiErrorResponse {
  success: false;
  code: ErrorCode;
  msg: string;
}

export type ErrorCode =
  | "WALLET_NOT_FOUND"
  | "USER_NOT_FOUND"
  | "FORBIDDEN"
  | "WALLET_ALREADY_EXISTS"
  | "API_KEYS_NOT_FOUND"
  | "DUPLICATE_PUBLIC_KEY"
  | "TSS_SESSION_NOT_FOUND"
  | "INVALID_TSS_SESSION"
  | "MISSING_CUSTOMER_ID"
  | "INVALID_TSS_STAGE"
  | "INVALID_TSS_TRIPLES_RESULT"
  | "INVALID_TSS_PRESIGN_RESULT"
  | "INVALID_TSS_SIGN_RESULT"
  | "CUSTOMER_ACCOUNT_NOT_FOUND"
  | "INVALID_EMAIL_OR_PASSWORD"
  | "EMAIL_NOT_VERIFIED"
  | "EMAIL_ALREADY_VERIFIED"
  | "VERIFICATION_CODE_ALREADY_SENT"
  | "FAILED_TO_SEND_EMAIL"
  | "INVALID_VERIFICATION_CODE"
  | "FAILED_TO_GENERATE_TOKEN"
  | "ORIGINAL_PASSWORD_INCORRECT"
  | "FAILED_TO_UPDATE_PASSWORD"
  | "AUTHENTICATION_FAILED"
  | "CUSTOMER_NOT_FOUND"
  | "UNAUTHORIZED"
  | "KEYSHARE_NODE_INSUFFICIENT"
  | "INVALID_REQUEST"
  | "INVALID_AUTH_TOKEN"
  | "INVALID_LOG"
  | "RATE_LIMIT_EXCEEDED"
  | "KS_NODE_NOT_FOUND"
  | "KS_NODE_ALREADY_INACTIVE"
  | "KS_NODE_ALREADY_ACTIVE"
  | "TSS_ACTIVATION_SETTING_NOT_FOUND"
  | "UNKNOWN_ERROR";
