/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Generate a 2-of-2 threshold Ed25519 key using centralized key generation.
 *
 * Returns a JSON object containing:
 * - `keygen_outputs`: Array of two key shares
 * - `public_key`: The Ed25519 public key (32 bytes)
 * - `private_key`: The original private key (for backup purposes only)
 */
export declare function napiKeygenCentralizedEd25519(): any
/**
 * Import an existing Ed25519 secret key and split it into threshold shares.
 *
 * # Arguments
 * * `secret_key` - A 32-byte array representing the Ed25519 secret key
 */
export declare function napiKeygenImportEd25519(secretKey: Array<number>): any
/**
 * Round 1: Generate signing commitments for a participant.
 *
 * # Arguments
 * * `key_package` - The participant's serialized KeyPackage
 *
 * Returns a JSON object containing:
 * - `nonces`: Serialized nonces (keep secret, use in round 2)
 * - `commitments`: Serialized commitments (send to coordinator)
 * - `identifier`: Participant identifier
 */
export declare function napiSignRound1Ed25519(keyPackage: Array<number>): any
/**
 * Round 2: Generate a signature share for a participant.
 *
 * # Arguments
 * * `message` - Message to sign
 * * `key_package` - The participant's serialized KeyPackage
 * * `nonces` - Nonces from round 1
 * * `all_commitments` - JSON array of CommitmentEntry objects
 */
export declare function napiSignRound2Ed25519(message: Array<number>, keyPackage: Array<number>, nonces: Array<number>, allCommitments: any): any
/**
 * Aggregate signature shares into a final threshold signature.
 *
 * # Arguments
 * * `message` - Message that was signed
 * * `all_commitments` - JSON array of CommitmentEntry objects
 * * `all_signature_shares` - JSON array of SignatureShareEntry objects
 * * `public_key_package` - Serialized PublicKeyPackage
 *
 * Returns a JSON object containing:
 * - `signature`: The 64-byte Ed25519 signature
 */
export declare function napiAggregateEd25519(message: Array<number>, allCommitments: any, allSignatureShares: any, publicKeyPackage: Array<number>): any
/**
 * Verify a signature against a public key.
 *
 * # Arguments
 * * `message` - Original message
 * * `signature` - 64-byte Ed25519 signature
 * * `public_key_package` - Serialized PublicKeyPackage
 *
 * Returns `true` if the signature is valid, `false` otherwise.
 */
export declare function napiVerifyEd25519(message: Array<number>, signature: Array<number>, publicKeyPackage: Array<number>): boolean
