name: "Bug report"
description: "Something isn't working as expected."
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug. You can attach screenshots or \
        logs
      placeholder: A concise description of the problem.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the exact steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened.
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Can't reproduce

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
        - Critical

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., v1.2.3

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS/Browser/Device/Runtime (e.g., macOS 14.5, Chrome 129, \
        NodeJS 22.10.0)
