/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'addon.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./addon.android-arm64.node')
          } else {
            nativeBinding = require('addon-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'addon.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./addon.android-arm-eabi.node')
          } else {
            nativeBinding = require('addon-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'addon.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./addon.win32-x64-msvc.node')
          } else {
            nativeBinding = require('addon-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'addon.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./addon.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('addon-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'addon.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./addon.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('addon-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'addon.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./addon.darwin-universal.node')
      } else {
        nativeBinding = require('addon-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'addon.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./addon.darwin-x64.node')
          } else {
            nativeBinding = require('addon-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'addon.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./addon.darwin-arm64.node')
          } else {
            nativeBinding = require('addon-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'addon.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./addon.freebsd-x64.node')
      } else {
        nativeBinding = require('addon-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'addon.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./addon.linux-x64-musl.node')
            } else {
              nativeBinding = require('addon-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'addon.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./addon.linux-x64-gnu.node')
            } else {
              nativeBinding = require('addon-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'addon.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./addon.linux-arm64-musl.node')
            } else {
              nativeBinding = require('addon-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'addon.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./addon.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('addon-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'addon.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./addon.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('addon-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'addon.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./addon.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('addon-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'addon.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./addon.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('addon-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'addon.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./addon.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('addon-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'addon.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./addon.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('addon-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { napiRunKeygenClientStep1, napiRunKeygenClientStep2, napiRunKeygenClientStep3, napiRunKeygenClientStep4, napiRunKeygenClientStep5, napiRunKeygenServerStep1, napiRunKeygenServerStep2, napiRunKeygenServerStep3, napiRunKeygenServerStep4, napiRunKeygenServerStep5, napiRunKeygenClientCentralized, napiRunKeygenCombineShares, napiRunPresignClientStep1, napiRunPresignClientStep2, napiRunPresignClientStep3, napiRunPresignServerStep1, napiRunPresignServerStep2, napiRunPresignServerStep3, napiRunSignClientStep1, napiRunSignClientStep1V2, napiRunSignClientStep2, napiRunSignServerStep1, napiRunSignServerStep1V2, napiRunSignServerStep2, napiRunTriples2ClientStep1, napiRunTriples2ClientStep2, napiRunTriples2ClientStep3, napiRunTriples2ClientStep4, napiRunTriples2ClientStep5, napiRunTriples2ClientStep6, napiRunTriples2ClientStep7, napiRunTriples2ClientStep8, napiRunTriples2ClientStep9, napiRunTriples2ClientStep10, napiRunTriples2ClientStep11, napiRunTriplesServerStep1, napiRunTriples2ServerStep1, napiRunTriples2ServerStep2, napiRunTriples2ServerStep3, napiRunTriples2ServerStep4, napiRunTriples2ServerStep5, napiRunTriples2ServerStep6, napiRunTriples2ServerStep7, napiRunTriples2ServerStep8, napiRunTriples2ServerStep9, napiRunTriples2ServerStep10, napiRunTriples2ServerStep11, napiRunVerify, napiRunVerify2 } = nativeBinding

module.exports.napiRunKeygenClientStep1 = napiRunKeygenClientStep1
module.exports.napiRunKeygenClientStep2 = napiRunKeygenClientStep2
module.exports.napiRunKeygenClientStep3 = napiRunKeygenClientStep3
module.exports.napiRunKeygenClientStep4 = napiRunKeygenClientStep4
module.exports.napiRunKeygenClientStep5 = napiRunKeygenClientStep5
module.exports.napiRunKeygenServerStep1 = napiRunKeygenServerStep1
module.exports.napiRunKeygenServerStep2 = napiRunKeygenServerStep2
module.exports.napiRunKeygenServerStep3 = napiRunKeygenServerStep3
module.exports.napiRunKeygenServerStep4 = napiRunKeygenServerStep4
module.exports.napiRunKeygenServerStep5 = napiRunKeygenServerStep5
module.exports.napiRunKeygenClientCentralized = napiRunKeygenClientCentralized
module.exports.napiRunKeygenCombineShares = napiRunKeygenCombineShares
module.exports.napiRunPresignClientStep1 = napiRunPresignClientStep1
module.exports.napiRunPresignClientStep2 = napiRunPresignClientStep2
module.exports.napiRunPresignClientStep3 = napiRunPresignClientStep3
module.exports.napiRunPresignServerStep1 = napiRunPresignServerStep1
module.exports.napiRunPresignServerStep2 = napiRunPresignServerStep2
module.exports.napiRunPresignServerStep3 = napiRunPresignServerStep3
module.exports.napiRunSignClientStep1 = napiRunSignClientStep1
module.exports.napiRunSignClientStep1V2 = napiRunSignClientStep1V2
module.exports.napiRunSignClientStep2 = napiRunSignClientStep2
module.exports.napiRunSignServerStep1 = napiRunSignServerStep1
module.exports.napiRunSignServerStep1V2 = napiRunSignServerStep1V2
module.exports.napiRunSignServerStep2 = napiRunSignServerStep2
module.exports.napiRunTriples2ClientStep1 = napiRunTriples2ClientStep1
module.exports.napiRunTriples2ClientStep2 = napiRunTriples2ClientStep2
module.exports.napiRunTriples2ClientStep3 = napiRunTriples2ClientStep3
module.exports.napiRunTriples2ClientStep4 = napiRunTriples2ClientStep4
module.exports.napiRunTriples2ClientStep5 = napiRunTriples2ClientStep5
module.exports.napiRunTriples2ClientStep6 = napiRunTriples2ClientStep6
module.exports.napiRunTriples2ClientStep7 = napiRunTriples2ClientStep7
module.exports.napiRunTriples2ClientStep8 = napiRunTriples2ClientStep8
module.exports.napiRunTriples2ClientStep9 = napiRunTriples2ClientStep9
module.exports.napiRunTriples2ClientStep10 = napiRunTriples2ClientStep10
module.exports.napiRunTriples2ClientStep11 = napiRunTriples2ClientStep11
module.exports.napiRunTriplesServerStep1 = napiRunTriplesServerStep1
module.exports.napiRunTriples2ServerStep1 = napiRunTriples2ServerStep1
module.exports.napiRunTriples2ServerStep2 = napiRunTriples2ServerStep2
module.exports.napiRunTriples2ServerStep3 = napiRunTriples2ServerStep3
module.exports.napiRunTriples2ServerStep4 = napiRunTriples2ServerStep4
module.exports.napiRunTriples2ServerStep5 = napiRunTriples2ServerStep5
module.exports.napiRunTriples2ServerStep6 = napiRunTriples2ServerStep6
module.exports.napiRunTriples2ServerStep7 = napiRunTriples2ServerStep7
module.exports.napiRunTriples2ServerStep8 = napiRunTriples2ServerStep8
module.exports.napiRunTriples2ServerStep9 = napiRunTriples2ServerStep9
module.exports.napiRunTriples2ServerStep10 = napiRunTriples2ServerStep10
module.exports.napiRunTriples2ServerStep11 = napiRunTriples2ServerStep11
module.exports.napiRunVerify = napiRunVerify
module.exports.napiRunVerify2 = napiRunVerify2
