/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as XCallbackIndexRouteImport } from './routes/x/callback/index'
import { Route as GoogleCallbackIndexRouteImport } from './routes/google/callback/index'
import { Route as Auth0CallbackIndexRouteImport } from './routes/auth0/callback/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const XCallbackIndexRoute = XCallbackIndexRouteImport.update({
  id: '/x/callback/',
  path: '/x/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleCallbackIndexRoute = GoogleCallbackIndexRouteImport.update({
  id: '/google/callback/',
  path: '/google/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth0CallbackIndexRoute = Auth0CallbackIndexRouteImport.update({
  id: '/auth0/callback/',
  path: '/auth0/callback/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/auth0/callback': typeof Auth0CallbackIndexRoute
  '/google/callback': typeof GoogleCallbackIndexRoute
  '/x/callback': typeof XCallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/auth0/callback': typeof Auth0CallbackIndexRoute
  '/google/callback': typeof GoogleCallbackIndexRoute
  '/x/callback': typeof XCallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/auth0/callback/': typeof Auth0CallbackIndexRoute
  '/google/callback/': typeof GoogleCallbackIndexRoute
  '/x/callback/': typeof XCallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth0/callback'
    | '/google/callback'
    | '/x/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/auth0/callback' | '/google/callback' | '/x/callback'
  id:
    | '__root__'
    | '/'
    | '/login/'
    | '/auth0/callback/'
    | '/google/callback/'
    | '/x/callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  Auth0CallbackIndexRoute: typeof Auth0CallbackIndexRoute
  GoogleCallbackIndexRoute: typeof GoogleCallbackIndexRoute
  XCallbackIndexRoute: typeof XCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/callback/': {
      id: '/x/callback/'
      path: '/x/callback'
      fullPath: '/x/callback'
      preLoaderRoute: typeof XCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google/callback/': {
      id: '/google/callback/'
      path: '/google/callback'
      fullPath: '/google/callback'
      preLoaderRoute: typeof GoogleCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth0/callback/': {
      id: '/auth0/callback/'
      path: '/auth0/callback'
      fullPath: '/auth0/callback'
      preLoaderRoute: typeof Auth0CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  Auth0CallbackIndexRoute: Auth0CallbackIndexRoute,
  GoogleCallbackIndexRoute: GoogleCallbackIndexRoute,
  XCallbackIndexRoute: XCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
