/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TelegramIndexRouteImport } from './routes/telegram/index'
import { Route as EmailIndexRouteImport } from './routes/email/index'
import { Route as XCallbackIndexRouteImport } from './routes/x/callback/index'
import { Route as TelegramCallbackIndexRouteImport } from './routes/telegram/callback/index'
import { Route as GoogleCallbackIndexRouteImport } from './routes/google/callback/index'
import { Route as EmailCallbackIndexRouteImport } from './routes/email/callback/index'
import { Route as DiscordCallbackIndexRouteImport } from './routes/discord/callback/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramIndexRoute = TelegramIndexRouteImport.update({
  id: '/telegram/',
  path: '/telegram/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailIndexRoute = EmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => rootRouteImport,
} as any)
const XCallbackIndexRoute = XCallbackIndexRouteImport.update({
  id: '/x/callback/',
  path: '/x/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramCallbackIndexRoute = TelegramCallbackIndexRouteImport.update({
  id: '/telegram/callback/',
  path: '/telegram/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleCallbackIndexRoute = GoogleCallbackIndexRouteImport.update({
  id: '/google/callback/',
  path: '/google/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailCallbackIndexRoute = EmailCallbackIndexRouteImport.update({
  id: '/email/callback/',
  path: '/email/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordCallbackIndexRoute = DiscordCallbackIndexRouteImport.update({
  id: '/discord/callback/',
  path: '/discord/callback/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email': typeof EmailIndexRoute
  '/telegram': typeof TelegramIndexRoute
  '/discord/callback': typeof DiscordCallbackIndexRoute
  '/email/callback': typeof EmailCallbackIndexRoute
  '/google/callback': typeof GoogleCallbackIndexRoute
  '/telegram/callback': typeof TelegramCallbackIndexRoute
  '/x/callback': typeof XCallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email': typeof EmailIndexRoute
  '/telegram': typeof TelegramIndexRoute
  '/discord/callback': typeof DiscordCallbackIndexRoute
  '/email/callback': typeof EmailCallbackIndexRoute
  '/google/callback': typeof GoogleCallbackIndexRoute
  '/telegram/callback': typeof TelegramCallbackIndexRoute
  '/x/callback': typeof XCallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email/': typeof EmailIndexRoute
  '/telegram/': typeof TelegramIndexRoute
  '/discord/callback/': typeof DiscordCallbackIndexRoute
  '/email/callback/': typeof EmailCallbackIndexRoute
  '/google/callback/': typeof GoogleCallbackIndexRoute
  '/telegram/callback/': typeof TelegramCallbackIndexRoute
  '/x/callback/': typeof XCallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email'
    | '/telegram'
    | '/discord/callback'
    | '/email/callback'
    | '/google/callback'
    | '/telegram/callback'
    | '/x/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email'
    | '/telegram'
    | '/discord/callback'
    | '/email/callback'
    | '/google/callback'
    | '/telegram/callback'
    | '/x/callback'
  id:
    | '__root__'
    | '/'
    | '/email/'
    | '/telegram/'
    | '/discord/callback/'
    | '/email/callback/'
    | '/google/callback/'
    | '/telegram/callback/'
    | '/x/callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailIndexRoute: typeof EmailIndexRoute
  TelegramIndexRoute: typeof TelegramIndexRoute
  DiscordCallbackIndexRoute: typeof DiscordCallbackIndexRoute
  EmailCallbackIndexRoute: typeof EmailCallbackIndexRoute
  GoogleCallbackIndexRoute: typeof GoogleCallbackIndexRoute
  TelegramCallbackIndexRoute: typeof TelegramCallbackIndexRoute
  XCallbackIndexRoute: typeof XCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/': {
      id: '/telegram/'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/': {
      id: '/email/'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/callback/': {
      id: '/x/callback/'
      path: '/x/callback'
      fullPath: '/x/callback'
      preLoaderRoute: typeof XCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/callback/': {
      id: '/telegram/callback/'
      path: '/telegram/callback'
      fullPath: '/telegram/callback'
      preLoaderRoute: typeof TelegramCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google/callback/': {
      id: '/google/callback/'
      path: '/google/callback'
      fullPath: '/google/callback'
      preLoaderRoute: typeof GoogleCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/callback/': {
      id: '/email/callback/'
      path: '/email/callback'
      fullPath: '/email/callback'
      preLoaderRoute: typeof EmailCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/callback/': {
      id: '/discord/callback/'
      path: '/discord/callback'
      fullPath: '/discord/callback'
      preLoaderRoute: typeof DiscordCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailIndexRoute: EmailIndexRoute,
  TelegramIndexRoute: TelegramIndexRoute,
  DiscordCallbackIndexRoute: DiscordCallbackIndexRoute,
  EmailCallbackIndexRoute: EmailCallbackIndexRoute,
  GoogleCallbackIndexRoute: GoogleCallbackIndexRoute,
  TelegramCallbackIndexRoute: TelegramCallbackIndexRoute,
  XCallbackIndexRoute: XCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
