import * as wasmModule from "../pkg/teddsa_wasm";

export { wasmModule };

// Flag to track module initialization status
let isInitialized = false;
// Store the initialized WASM module
let wasmInstance: typeof wasmModule | null = null;
// Store exported functions
const exportedFunctions: Record<string, Function> = {};

type WasmModule = typeof wasmModule;
export type WasmFunctionNames = keyof WasmModule;

/**
 * Function to initialize WASM module and export its functions globally
 *
 * @param wasmMod - WASM module (import * as wasmModule from "my-wasm-module")
 * @param wasmPath - WASM binary file path (default: "/teddsa_wasm_bg.wasm")
 * @returns Object containing all exported functions
 */
export async function initWasm(
  wasmMod: typeof wasmModule,
  wasmPath: string,
): Promise<Record<string, Function>> {
  // Return cached functions if already initialized
  if (isInitialized && wasmInstance) {
    return exportedFunctions;
  }

  try {
    // Load WASM binary file
    const response = await fetch(wasmPath);
    if (!response.ok) {
      throw new Error(
        `Cannot load WASM file: ${response.status} ${response.statusText}`,
      );
    }

    const wasmBytes = await response.arrayBuffer();

    // Initialize WASM module - initSync is a function generated by wasm-bindgen
    (wasmMod as any).initSync(wasmBytes);

    // Store the initialized module
    wasmInstance = wasmMod;

    // Extract all functions from the module
    Object.keys(wasmMod)
      .filter((key) => typeof (wasmMod as any)[key] === "function")
      .forEach((funcName) => {
        // Create a wrapper function that calls the WASM function
        exportedFunctions[funcName] = (...args: unknown[]) =>
          (wasmMod as any)[funcName](...args);
      });

    // Mark initialization as successful
    isInitialized = true;

    return exportedFunctions;
  } catch (error) {
    throw error;
  }
}

/**
 * Helper function to check if WASM is initialized
 */
export function isWasmInitialized(): boolean {
  return isInitialized;
}
