export {
  authTypeSchema,
  CheckKeyShareRequestBodySchema,
  CheckKeyShareResponseSchema,
  CheckKeyShareSuccessResponseSchema,
  curveTypeSchema,
  GetKeyShareRequestBodySchema,
  GetKeyShareResponseSchema,
  GetKeyShareSuccessResponseSchema,
  KeyShareEmptySuccessResponseSchema,
  publicKeySchema,
  RegisterKeyShareBodySchema,
  ReshareKeyShareBodySchema,
  shareSchema,
} from "./key_share_v1";
export {
  CheckKeyShareV2RequestBodySchema,
  CheckKeyShareV2ResponseSchema,
  CheckKeyShareV2SuccessResponseSchema,
  GetKeyShareV2RequestBodySchema,
  GetKeyShareV2ResponseSchema,
  GetKeyShareV2SuccessResponseSchema,
  RegisterEd25519V2RequestBodySchema,
  RegisterEd25519V2SuccessResponseSchema,
  RegisterKeyShareV2RequestBodySchema,
  RegisterKeyShareV2SuccessResponseSchema,
  ReshareKeyShareV2RequestBodySchema,
  ReshareKeyShareV2SuccessResponseSchema,
  ReshareRegisterV2RequestBodySchema,
  ReshareRegisterV2SuccessResponseSchema,
  walletsRequestBodySchema,
} from "./key_share_v2";
