/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function napiRunKeygenClientStep1(): any
export declare function napiRunKeygenClientStep2(st0Json: any, msgs0Json: any): any
export declare function napiRunKeygenClientStep3(st0Json: any, msgs0Json: any): any
export declare function napiRunKeygenClientStep4(st0Json: any, msgs0Json: any): any
export declare function napiRunKeygenClientStep5(st0Json: any, msgs0Json: any): any
export declare function napiRunKeygenServerStep1(): any
export declare function napiRunKeygenServerStep2(st1Json: any, msgs1Json: any): any
export declare function napiRunKeygenServerStep3(st1Json: any, msgs1Json: any): any
export declare function napiRunKeygenServerStep4(st1Json: any, msgs1Json: any): any
export declare function napiRunKeygenServerStep5(st1Json: any, msgs1Json: any): any
export declare function napiRunKeygenClientCentralized(): any
export declare function napiRunKeygenCombineShares(keyCombineInputJson: any): any
export declare function napiRunPresignClientStep1(pub0Json: any, pub1Json: any, share00Json: any, share01Json: any, keygen0Json: any): any
export declare function napiRunPresignClientStep2(st0Json: any): any
export declare function napiRunPresignClientStep3(st0Json: any, msgs0Json: any): any
export declare function napiRunPresignServerStep1(pub0Json: any, pub1Json: any, share01Json: any, share11Json: any, keygen1Json: any): any
export declare function napiRunPresignServerStep2(st1Json: any): any
export declare function napiRunPresignServerStep3(st1Json: any, msgs1Json: any): any
export declare function napiRunSignClientStep1(msg: string, presig0Json: any): any
export declare function napiRunSignClientStep1V2(msg: Uint8Array, presig0Json: any): any
export declare function napiRunSignClientStep2(st0Json: any, msgs0Json: any, presig0Json: any): any
export declare function napiRunSignServerStep1(msg: string, presig1Json: any): any
export declare function napiRunSignServerStep1V2(msg: Uint8Array, presig1Json: any): any
export declare function napiRunSignServerStep2(st1Json: any, msgs1Json: any, presig1Json: any): any
export declare function napiRunTriples2ClientStep1(): any
export declare function napiRunTriples2ClientStep2(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep3(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep4(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep5(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep6(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep7(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep8(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep9(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep10(st0Json: any, msgs0Json: any): any
export declare function napiRunTriples2ClientStep11(st0Json: any, msgs0Json: any): any
export declare function napiRunTriplesServerStep1(): any
export declare function napiRunTriples2ServerStep1(): any
export declare function napiRunTriples2ServerStep2(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep3(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep4(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep5(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep6(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep7(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep8(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep9(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep10(st1Json: any, msgs1Json: any): any
export declare function napiRunTriples2ServerStep11(st1Json: any, msgs1Json: any): any
export declare function napiRunVerify(fullSig: any, publicKey: any, msg: string): any
export declare function napiRunVerify2(fullSig: any, publicKey: any, msg: Uint8Array): any
