/**
 * This file is autogenerated by generateAbis.ts
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "@oko-wallet-sandbox-evm/utils/scaffold-eth/contract";

const deployedContracts = {} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
